name: Daily AI News Update

on:
  schedule:
    - cron: '30 9 * * *'  # This runs at 9:30 AM UTC every day
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:  # Add this: Grants write access for pushes
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Fetch AI news
      run: python fetch_ai_news.py  # This runs the script
      env:
        XAI_API_KEY: ${{ secrets.XAI_API_KEY }}

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add news/* index.json
        git commit -m "Update daily AI news [$(date +%Y-%m-%d)]" || exit 0
        git push