import requests
import json
import os
from datetime import datetime

# Define the prompt
prompt = """Summarize the most significant artificial intelligence and technology developments in the past 24 hours, including new tools, updates, and announcements. Focus on model releases, new papers, and open-source projects, and provide relevant links."""

# API endpoint and configuration
url = "https://api.x.ai/v1/chat/completions"
api_key = os.getenv("XAI_API_KEY")  # Load from environment variable

if not api_key:
    raise ValueError("XAI_API_KEY environment variable is not set. Please set it in your environment or GitHub Actions secrets.")

headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json"
}

data = {
    "messages": [
        {"role": "user", "content": prompt}
    ],
    "model": "grok-4",  # Use the latest model; check https://docs.x.ai/docs/models for available models
    "stream": False
}

# Make the API call
response = requests.post(url, headers=headers, json=data)

if response.status_code != 200:
    raise Exception(f"API request failed with status code {response.status_code}: {response.text}")

result = response.json()["choices"][0]["message"]["content"]

# Prepare data with timestamp
timestamp = datetime.now().isoformat()
news_data = {
    "timestamp": timestamp,
    "summary": result
}

# Ensure news/ directory exists
os.makedirs("news", exist_ok=True)

# Save to JSON file (using timestamp in filename for uniqueness)
filename = f"news/grok_news_summary_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.json"
with open(filename, "w", encoding="utf-8") as f:
    json.dump(news_data, f, indent=4, ensure_ascii=False)

print(f"Summary saved to {filename}")